### ISSUE TITLE
Milestone 3 Feedback 

### ISSUE THREAD

**Issue by evelynmoorhouse** [UBC-MDS/DSCI532_GROUP104_Movies#67]
Hi all,

Great app! 

Things we liked:
- The one line description was useful and to the point
- The drop down bar being included in the description was a good idea, the user knew how to use it immediately.

Feedback:
- Changing the initial profit and rating plots so that not all of the directors show, would make the plots more useful initially without having to select specific directors. 

- Changing the layout of the app so that the user does not need to scroll to the right to see the full names of the directors in the legend.

**Comment by sweber15** [comment]
Compiled feedback issues: https://github.com/UBC-MDS/DSCI532_GROUP104_Movies/issues/69
