### ISSUE TITLE
Peer feedback

### ISSUE THREAD

**Issue by HanyingZhang** [UBC-MDS/DSCI532_GROUP104_Movies#68]
The dashboard is really fancy, but something here appears to be a little bit confusing:
- The title says "top 30 most productive directors" for each category, but some genre contains less than 30 directors in the bar chart, which is opposite to the title;
- The trend becomes a bit messy when many directors are selected.

**Comment by sweber15** [comment]
Thank you for your feedback.

Complied feedback here: https://github.com/UBC-MDS/DSCI532_GROUP104_Movies/issues/69
